wandb_version: 1

vocab_size:
  desc: null
  value: 15
context_length:
  desc: null
  value: 19
model_size:
  desc: null
  value: 128
num_heads:
  desc: null
  value: 8
num_blocks:
  desc: null
  value: 4
device:
  desc: null
  value: cuda
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726019518
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.17.9
      8:
      - 5
      13: linux-x86_64
